# Keybind reference: Alt+/ opens ~/.config/tmux/tmux-reference.txt

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

bind -n M-d split-window -h
bind -n M-D split-window -v

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -rn C-h resize-pane -L 5
bind -rn C-j resize-pane -D 5
bind -rn C-k resize-pane -U 5
bind -rn C-l resize-pane -R 5

bind -n M-H previous-window
bind -n M-L next-window

bind -n M-n new-window
bind -n M-w kill-pane
bind -n M-f resize-pane -Z
bind -n M-/ display-popup -w 54 -h 30 -E "less ~/.config/tmux/tmux-reference.txt"

bind-key -T copy-mode-vi v send-keys -X begin-selection
