set -g status-style "bg=default,fg=#53685B"
set -g status-left "#[fg=#549e6a]#S "
set -g status-right ""
set -g status-left-length 20
set -g status-justify absolute-centre

set -g window-status-format "#[fg=#53685B] #I:#W "
set -g window-status-current-format "#[fg=#C1C497] #I:#W "

set -g pane-border-style "fg=#23372B"
set -g pane-active-border-style "fg=#549e6a"
set -g pane-border-indicators off
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=#549e6a] #{s/^[0-9][0-9.]*$/claude/:pane_current_command} ,}"

set -g window-style "fg=#888888"
set -g window-active-style "fg=terminal"
set -g message-style "bg=#23372B,fg=#C1C497"
