set -g default-terminal "tmux-256color"
set -g terminal-features "xterm*:clipboard:ccolour:cstyle:focus:title,*:RGB,xterm-ghostty:hyperlinks:clipboard:extkeys,tmux-256color:hyperlinks"
set -g update-environment "TERM TERM_PROGRAM TERM_PROGRAM_VERSION COLORTERM SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

set -g extended-keys always
set -g extended-keys-format csi-u
set -g xterm-keys on

set -g set-clipboard on
set -g allow-passthrough off
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[6 q'
