set -g default-terminal "tmux-256color"
set -g terminal-features "*:RGB,xterm-ghostty:extkeys,xterm-kitty:extkeys"

set -g extended-keys always
set -g extended-keys-format csi-u
set -g xterm-keys on

set -g set-clipboard on
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[6 q'
